import { describe, expect, test, jest } from '@jest/globals';

// Check if GPU is available and has sufficient memory
const hasGPU = process.env.HAS_GPU === 'true';
const gpuMemGB = parseFloat(process.env.GPU_MEM_GB || '0');
const minRequiredMemGB = 5;

// Skip tests if GPU requirements are not met
const shouldRunTests = hasGPU && gpuMemGB >= minRequiredMemGB;

// This is a conditional test suite that only runs when GPU is available
(shouldRunTests ? describe : describe.skip)('smollm-webgpu language model tests', () => {
	// Mock the WebGPU API since Jest runs in Node.js
	beforeAll(() => {
		// Only setup mocks if we're actually running tests
		if (shouldRunTests) {
			global.navigator = {
				gpu: {
					requestAdapter: jest.fn().mockResolvedValue({
						requestDevice: jest.fn().mockResolvedValue({
							createBuffer: jest.fn(),
							createCommandEncoder: jest.fn(),
							queue: { submit: jest.fn() }
						})
					})
				}
			};
		}
	});

	test('WebGPU device can be acquired', async () => {
		// This is a simple test to verify WebGPU availability
		const adapter = await navigator.gpu.requestAdapter();
		const device = await adapter.requestDevice();

		expect(device).toBeDefined();
		expect(typeof device.createBuffer).toBe('function');
	});

	test('Language model can generate text', async () => {
		// This is a simplified test of the LLM generation functionality

		// Mock pipeline function that simulates text generation
		const mockPipeline = jest.fn().mockImplementation(() => {
			return async (text) => {
				return { generated_text: "This is a response generated by SmolLM model." };
			};
		});

		// Create a mock generator function
		const generate = async (prompt) => {
			const pipe = mockPipeline('text-generation');
			return await pipe(prompt);
		};

		// Test text generation
		const result = await generate("What is machine learning?");
		expect(result.generated_text).toBeDefined();
		expect(typeof result.generated_text).toBe('string');
		expect(result.generated_text).toContain("response generated by SmolLM");
	});
});

// This test always runs to verify the GPU check logic
describe('GPU availability check for smollm-webgpu', () => {
	test('GPU requirements are checked correctly', () => {
		console.log(`GPU available: ${hasGPU}, GPU memory: ${gpuMemGB}GB, Required: ${minRequiredMemGB}GB`);

		if (!shouldRunTests) {
			console.log('Skipping SmolLM WebGPU tests due to insufficient GPU resources');
		}

		// This just verifies our environment variables are parsed correctly
		expect(typeof hasGPU).toBe('boolean');
		expect(typeof gpuMemGB).toBe('number');
	});
});
