services:
  debt-scanner:
    build:
      context: ../..
      dockerfile: .github/debt-management/docker/Dockerfile
    volumes:
      - ../../..:/repo
      - ../../runner-images:/runner-images-src:ro
      - runner-images-build:/runner-images-build
    environment:
      - TERM=xterm-color
      - RUNNER_IMAGES_TOKEN=${RUNNER_IMAGES_TOKEN}
    tty: true
volumes:
  runner-images-build:
    driver: local