# COMPOSE_ID::HEADER
# filepath: c:\Projects\transformers.js-examples\.github\debt-management\docker\docker-compose.yml
# COMPOSE_META::DESCRIPTION
# Docker Compose configuration for debt management assistant
# COMPOSE_META::VERSION
# Version: 1.0.0

# COMPOSE_VERSION
version: '3.8'

# COMPOSE_SERVICES
services:
  # COMPOSE_SERVICE::DEBT_ASSISTANT
  debt-assistant:
    # COMPOSE_BUILD::DOCKERFILE
    build:
      context: .
      dockerfile: Dockerfile
    # COMPOSE_SERVICE_IMAGE
    image: debt-management-assistant:latest
    # COMPOSE_SERVICE_CONTAINER_NAME
    container_name: debt-management-assistant
    # COMPOSE_SERVICE_RESTART
    restart: unless-stopped
    # COMPOSE_SERVICE_VOLUMES
    volumes:
      - ../config:/app/config:rw
      - ../reports:/app/debt-reports:rw
      - model-cache:/app/model-cache
      - ./scripts:/app/scripts:ro
    # COMPOSE_SERVICE_ENV
    environment:
      - NODE_ENV=production
      - CONFIG_DIR=/app/config
      - REPORTS_DIR=/app/debt-reports
      - MODEL_CACHE_DIR=/app/model-cache
      - TZ=UTC
    # COMPOSE_SERVICE_HEALTHCHECK
    healthcheck:
      test: ["CMD", "node", "/app/scripts/health-check.js"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    # COMPOSE_SERVICE_COMMAND
    command: ["node", "/app/scripts/debt-assistant.js", "--scan", "/app/repo"]
    # COMPOSE_SERVICE_LABELS
    labels:
      org.opencontainers.image.title: "Debt Management Assistant"
      org.opencontainers.image.description: "AI-powered technical debt management system"
      org.opencontainers.image.version: "1.0.0"

# COMPOSE_VOLUMES
volumes:
  # COMPOSE_VOLUME::MODEL_CACHE
  model-cache:
    # COMPOSE_VOLUME_DRIVER
    driver: local

# COMPOSE_ID::FOOTER
# SchemaVersion: 1.0.0
# ComposeID: debt-management-assistant
