version: '3.8'

services:
  janus-webgpu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - REQUIRES_GPU=true
      - MIN_GPU_MEMORY=5
    # Configure GPU access - required for WebGPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
