version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.ssh:/home/node/.ssh
      - node_modules_volume:/workspace/node_modules
      - azure_config_volume:/home/node/.azure
      - precompiled_volume:/workspace/.precompiled
      - build_cache_volume:/root/.cache
      - ./volumes/config:/workspace/.config:cached
    environment:
      - NODE_ENV=development
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - BUILDKIT_PROGRESS=plain
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    privileged: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    command: sleep infinity

  # Azure Storage Emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data

volumes:
  node_modules_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volumes/node_modules
  azure_config_volume:
    driver: local
  precompiled_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volumes/precompiled
  build_cache_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volumes/cache
  azurite_data:
    driver: local
